gemini:
    api-key: AIzaSyBXSg_1Co3w-2v1JgluJlmWidZjMLROI2k
    model : gemini-2.0-flash

audit:
    criteria:
        - offensive language
        - controversial opinions
        - embarrassing content
        - professional reputation risk   